services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caf-api-container
    image: caf-api-image
    ports:
      - '7006:8080'
    restart: on-failure

  postgres:
    image: 'postgres:latest'
    container_name: db
    restart: always
    environment:
      - 'POSTGRES_DB=tournament_db'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=president'
    ports:
      - '5432:5432'
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"