application:
  security:
    jwt:
      secret-key: asdfSFS34wfiewu9203iod023ndnwu2ionlews232dgdf4
      access-token:
        expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    jcache:
      config: classpath:ehcache.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: example@email.com
    password: rruesd0iinsdisd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#  web:
#    cors:
#      allowed-origins: "*"
#      allowed-methods: GET,POST,PUT,PATCH, DELETE
#      allowed-headers: "*"
#      allow-credentials: true
#      max-age: 3600