server:
  port: 7006
application:
  security:
    jwt:
      secret-key: asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4
      access-token:
        expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
spring:
  datasource:
    url: jdbc:postgresql://db:6005/tournament_db
    username: president
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  cache:
    ehcache:
      config: classpath:ehcache.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: richard.bouaro@amalitech.com
    password: snixhmkmrafjmgri
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#  web:
#    cors:
#      allowed-origins: "*"
#      allowed-methods: GET,POST,PUT,PATCH, DELETE
#      allowed-headers: "*"
#      allow-credentials: true
#      max-age: 3600